### ISSUE TITLE
No BFOTF Option

### ISSUE THREAD

**Issue by jams2022** [TheFearsomeDzeraora/NintyFont#3]
I see that there`s no bfotf option to encrypt fonts with just the BFTTF option.

**Comment by hadashisora** [comment]
The crypto is exactly the same between BFTTF and BFOTF, so that single menu works for both. In fact, if you hover over the options under the BFTTF menu, the description thing in the status bar will tell you it's for both, and the file dialogues allow you to select both file types.
 I guess in later revisions I'll edit the buttons to say `BFTTF/BFOTF` to make it more clear.
