### ISSUE TITLE
Is the project dead why still no BFFNT support?

### ISSUE THREAD

**Issue by tomxhachijuroku** [TheFearsomeDzeraora/NintyFont#5]
Hello, I love this program it helped me a lot in my fan translations, but I was wondering is it still worked on, because I need a BFFNT font editor for 3ds\Switch games, please, tell me if it's going to be added in a future build, or is the project dead, and I still need to rely on replacing and not adding new characters, thank you in advance.

**Comment by hadashisora** [comment]
Hi. I'm glad my program turned out to be useful for your projects!
Sadly due to lack of motivation (and really the desire to refactor the code and make it not crap, as this was basically my first big C++ project) I've not really worked on this thing for more than a year now, despite starting to rewrite the code. I'm not sure if I'll ever return to completing either this program or a successor to it, so you can essentially consider the project dead, unless someone else wants to fork and revive it. Or unless I return to it when I get the time and motivation for it. Sorry for the inconvenience...

As for alternatives, if you don't mind getting your hands dirty with the leaked official SDK tools, you can use the bundled fontcvtr application (part of Nintendo Ware) to do the edits. I've made a tool in the past that would help with this, and also has (a pretty terrible) guide on how to it. You can find it in the [XLORify-Sharp repo](https://github.com/hadashisora/XLORify-Sharp).
